"""init

Revision ID: 41e7a9814ce5
Revises: 
Create Date: 2019-06-17 12:03:47.433930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e7a9814ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combatiente',
    sa.Column('idCombatiente', sa.String(length=28), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('iniciativa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('reflejos', sa.Integer(), nullable=False),
    sa.Column('velocidadArma', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idCombatiente')
    )
    op.create_index(op.f('ix_combatiente_iniciativa'), 'combatiente', ['iniciativa'], unique=False)
    op.create_table('habilidad_base',
    sa.Column('idHabilidad', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.String(length=420), nullable=True),
    sa.Column('bonusPrincipal', sa.String(), nullable=False),
    sa.Column('bonusSecundario', sa.String(), nullable=False),
    sa.Column('combate', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idHabilidad')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.String(length=28), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('contrasena', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiracion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_index(op.f('ix_usuario_alias'), 'usuario', ['alias'], unique=True)
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_token'), 'usuario', ['token'], unique=True)
    op.create_table('combate',
    sa.Column('idCombate', sa.String(length=28), nullable=False),
    sa.Column('descripcion', sa.String(length=140), nullable=True),
    sa.Column('master_id', sa.String(length=28), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('turno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idCombate')
    )
    op.create_table('personaje',
    sa.Column('idPersonaje', sa.String(length=28), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('cultura', sa.String(length=64), nullable=True),
    sa.Column('raza', sa.String(length=64), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('procedencia', sa.String(length=64), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('caracteristicas', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.String(length=28), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('idPersonaje')
    )
    op.create_index(op.f('ix_personaje_cultura'), 'personaje', ['cultura'], unique=False)
    op.create_index(op.f('ix_personaje_nombre'), 'personaje', ['nombre'], unique=False)
    op.create_index(op.f('ix_personaje_procedencia'), 'personaje', ['procedencia'], unique=False)
    op.create_index(op.f('ix_personaje_raza'), 'personaje', ['raza'], unique=False)
    op.create_table('PJS',
    sa.Column('pj_id', sa.String(length=28), nullable=False),
    sa.Column('combate_id', sa.String(length=28), nullable=False),
    sa.ForeignKeyConstraint(['combate_id'], ['combate.idCombate'], ),
    sa.ForeignKeyConstraint(['pj_id'], ['combatiente.idCombatiente'], ),
    sa.PrimaryKeyConstraint('pj_id', 'combate_id')
    )
    op.create_table('PNJS',
    sa.Column('pnj_id', sa.String(length=28), nullable=False),
    sa.Column('combate_id', sa.String(length=28), nullable=False),
    sa.ForeignKeyConstraint(['combate_id'], ['combate.idCombate'], ),
    sa.ForeignKeyConstraint(['pnj_id'], ['combatiente.idCombatiente'], ),
    sa.PrimaryKeyConstraint('pnj_id', 'combate_id')
    )
    op.create_table('habilidad_personaje',
    sa.Column('idHabilidadPersonaje', sa.String(length=64), nullable=False),
    sa.Column('habilidad_id', sa.String(length=64), nullable=False),
    sa.Column('personaje_id', sa.String(length=28), nullable=False),
    sa.Column('valorBase', sa.Integer(), nullable=False),
    sa.Column('extra', sa.Integer(), nullable=True),
    sa.Column('pap', sa.Integer(), nullable=True),
    sa.Column('habilidadUsada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidad_base.idHabilidad'], ),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.idPersonaje'], ),
    sa.PrimaryKeyConstraint('idHabilidadPersonaje'),
    sa.UniqueConstraint('habilidad_id', 'personaje_id', name='unique_personaje_habilidad')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habilidad_personaje')
    op.drop_table('PNJS')
    op.drop_table('PJS')
    op.drop_index(op.f('ix_personaje_raza'), table_name='personaje')
    op.drop_index(op.f('ix_personaje_procedencia'), table_name='personaje')
    op.drop_index(op.f('ix_personaje_nombre'), table_name='personaje')
    op.drop_index(op.f('ix_personaje_cultura'), table_name='personaje')
    op.drop_table('personaje')
    op.drop_table('combate')
    op.drop_index(op.f('ix_usuario_token'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_alias'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('habilidad_base')
    op.drop_index(op.f('ix_combatiente_iniciativa'), table_name='combatiente')
    op.drop_table('combatiente')
    # ### end Alembic commands ###
